

meta_product_name: "Nom du Product"
meta_title: "Poseidon - Find your surf classes"
meta_description: "find your surf classes"
meta_image: "http://res.cloudinary.com/dyub4bz6x/image/upload/v1503049553/POSEIDON_lv5ura.png"                           # Une image dans votre dossier app/assets/images/

twitter_account: "@nomdevotrecompte"
